#! /usr/bin/python3

################################################################################
# flexiWAN SD-WAN software - flexiEdge, flexiManage.
# For more information go to https://flexiwan.com
#
# Copyright (C) 2019  flexiWAN Ltd.
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
################################################################################
import json
import fwglobals
import fwutils
from fwobject import FwObject
import fw_acl_command_helpers

class FwFirewall(FwObject):
    """
    Flexiwan Firewall class:
    The class encapsulates all the ACL attachment contexts and the context of
    global Identity NATs (edge access rules). It maintains context of per
    interface ACLs data. The maintained contexts aid in handling attachments
    during dynamic interfaces creation and deletion.

    :param FwObject: Flexiwan object that has common contexts like logger
    :type FwObject: Object
    """

    def __init__(self):
        """
        Inits all local contexts
        """
        self.db = fwglobals.g.create_sqlite_dict(fwglobals.g.FIREWALL_DB_FILE)
        FwObject.__init__(self)

    def __enter__(self):
        """
        Entry function that gets called when using the 'with' construct

        :return: Firewall class instance
        :rtype: Firewall class instance
        """
        return self

    def __exit__(self, exc_type, exc_value, traceback):
        """
        Exit function that gets called when using the 'with' construct.
        """
        return None

    def dumps(self):
        """
        Dumps the firewall DB as json string output

        :return: Firewall DB returned as json string
        :rtype: String
        """
        db_keys = sorted(self.db.keys())
        dump = [ { key: self.db[key] } for key in db_keys ]
        return json.dumps(dump, indent=2, sort_keys=True)

    def reset(self, reset_vxlan_nat_processed=False):
        """
        Reset the firewall DB context

        :param reset_vxlan_nat_processed: Flag to indicate if vxlan_nat_processed state has to be
        reset, defaults to False
        :type reset_vxlan_nat_processed: bool, optional
        """
        self.db.put('firewall_processed', False)
        self.db.put('keys_to_acls', {})
        self.db.put('interfaces', {})
        if reset_vxlan_nat_processed:
            self.db.put('vxlan_nat_processed', False)

    def is_firewall_processed (self):
        """
        Get function to know if firewall message has been processed

        :return: True if processed else False
        :rtype: bool
        """
        return self.db.fetch('firewall_processed', False)

    def set_firewall_processed (self):
        """
        Set function to mark the firewall_processed state to True
        """
        return self.db.put('firewall_processed', True)

    def add_acl_key (self, acl_key):
        """
        Add the ACL key that maps to the ACL id generated by the VPP

        :param acl_key: Unique key to identify corresponding VPP ACL ID
        :type acl_key: String
        """
        path = f'keys_to_acls/{acl_key}'
        self.db.put(path, None)

    def get_acl_id (self, acl_key):
        """
        Get the VPP ACL ID for the given key that uniquely represents it

        :param acl_key: Unique key to identify corresponding VPP ACL ID
        :type acl_key: String
        :return: VPP ACL ID
        :rtype: Integer
        """
        path = f'keys_to_acls/{acl_key}'
        return self.db.fetch(path, None)

    def add_to_acl_interfaces (self, sw_if_index):
        """
        Add the given VPP interface identifier to the ACL-interface-attachment contexts

        :param sw_if_index: Unique identifier that represents an interface within VPP
        :type sw_if_index: Integer
        """
        path = f'interfaces/{sw_if_index}'
        self.db.put(path, True)

    def get_acl_interfaces (self):
        """
        Get the interfaces that are tracked for ACL attachments
        :return: sw_if_indexes of ACL-interface-attachment contexts
        :rtype: dict
        """
        return self.db.fetch('interfaces', {})

    def is_acl_interface (self, sw_if_index):
        """
        Function to indicate if a given interface has ACL attachments

        :param sw_if_index: Unique identifier that represents an interface within VPP
        :type sw_if_index: Integer
        :return: Flag indicating if it is an interface with ACL attachments or not
        :rtype: Boolean
        """
        path = f'interfaces/{sw_if_index}'
        return self.db.fetch(path, False)

    def remove_from_acl_interfaces (self, sw_if_index):
        """
        Mark the given interface identifier in the dict as false for ACL-attachment-state

        :param sw_if_index: Unique identifier that represents an interface within VPP
        :type sw_if_index: Integer
        """
        path = f'interfaces/{sw_if_index}'
        self.db.delete(path)


    def set_acl_keys_to_acl_id(self, cmd_cache):
        """
        Map the ACL keys to the corresponding VPP ACL ID. The command cache is used
        to query the ACL ID for the corresponding ACL key

        :param cmd_cache: A cache where executed commands add key value pairs that can be used by
        the later commands to fill the required contexts
        :type cmd_cache: dict
        """
        keys_to_acls = self.db.fetch('keys_to_acls', {})
        for acl_key in keys_to_acls.keys():
            path = f'keys_to_acls/{acl_key}'
            self.db.put(path, cmd_cache[acl_key])

    def get_vxlan_nat_processed (self):
        """
        Returns if VxLAN firewall state has been already set by the add-vxlan message

        :return: Flag indicating if VxLAN NAT state has been processed by the add-vxlan message flow
        :rtype: bool
        """
        return self.db.fetch('vxlan_nat_processed', False)

    def set_vxlan_nat_processed (self, add):
        """
        Mark VxLAN message as processed or removed based on the given flag

        :param add: Flag indicating if VxLAN message is processed or not
        :type add: bool
        """
        self.db.put('vxlan_nat_processed', add)

def get_ids_to_acl_mapping():
    with FwFirewall() as firewall:
        return firewall.db.get('keys_to_acls', {})

def clean_db(reset_vxlan_nat_processed):
    """
    Encapsulates the firewall object's reset(). The encapsulation
    ensures the db is opened and closed cleanly

    :param reset_vxlan_nat_processed: _description_
    :type reset_vxlan_nat_processed: _type_
    """
    with FwFirewall() as firewall:
        firewall.reset(reset_vxlan_nat_processed)

def map_acl_keys_to_acl_id(cmd_cache):
    """
    Encapsulates the firewall object's set_acl_keys_to_acl_id(). The encapsulation
    ensures the db is opened and closed cleanly

    :param cmd_cache: A cache where commands add key value pairs that can be used by
    later commands to fill required contexts
    :type cmd_cache: dict
    """
    with FwFirewall() as firewall:
        firewall.set_acl_keys_to_acl_id (cmd_cache)

def is_vxlan_nat_processed ():
    """
    Encapsulates the firewall object's get_vxlan_nat_processed(). The encapsulation
    ensures the db is opened and closed cleanly

    :return: Flag indicating if VxLAN NAT state has been processed by the add-vxlan message flow
    :rtype: bool
    """
    with FwFirewall() as firewall:
        return firewall.get_vxlan_nat_processed()

def update_vxlan_nat_processed (add):
    """
    Encapsulates the firewall object's set_vxlan_nat_processed(). The encapsulation
    ensures the db is opened and closed cleanly

    :param add: Flag indicating if VxLAN message is processed or not
    :type add: bool
    """
    with FwFirewall() as firewall:
        firewall.set_vxlan_nat_processed(add)

def setup_firewall_iptables_rules (is_add, dev_id):
    """
    Setup / Clear iptables rules on the given device identifier. This API is the entry
    call for firewall post creation or deletion of dynamic loopback interfaces.

    :param is_add: Flag to indicate setup or delete config
    :type is_add: Boolean
    :param dev_id: Unique identifier of the device
    :type dev_id: String
    """

    firewall_policy_params = fwglobals.g.router_api.cfg_db.get_firewall_policy()
    if not firewall_policy_params:
        return
    outbound_rules = firewall_policy_params.get('outbound')

    for rule_index, rule in enumerate(outbound_rules['rules']):

        classification = rule.get('classification')
        if classification:
            destination = classification.get('destination')
            source = classification.get('source')
        else:
            destination = None
            source = None

        action = rule['action']
        permit = action['permit']
        # interfaces ['Array of LAN device ids] received from flexiManage
        dev_ids = action.get('interfaces', [])

        if dev_id in dev_ids:
            try:
                if_address = fwutils.get_interface_address(dev_id=dev_id)
            except:
                if_address = None

            if if_address:
                fw_acl_command_helpers.exec_iptables_rules(is_add, if_address, source, destination, permit)
            else:
                fwglobals.log.error(f'Outbound firewall: Cannot get ip address for interface {dev_id}')

    return

def get_stats(reset=False):
    if reset:
        fwglobals.g.router_api.vpp_api.vpp.call('acl_reset_counters')

    stats = {}
    firewall_db_mapping = get_ids_to_acl_mapping()
    firewall = fwglobals.g.router_api.vpp_api.vpp.call('acl_get_counters')
    for rule_id, rule_acl_index in firewall_db_mapping.items():
        if 'egress' in rule_id:
            continue

        rule_manage_id = rule_id.split(':')[0]
        stats[rule_manage_id] = firewall.matches[rule_acl_index]

    return stats
